#pragma once

#define MOTOR_WHEELS_LEFT_FRONT  9
#define MOTOR_WHEELS_LEFT_BACK   9
#define MOTOR_WHEELS_RIGHT_FRONT 4
#define MOTOR_WHEELS_RIGHT_BACK  5

#define MOTOR_LIFT_1 6
#define MOTOR_LIFT_2 7
#define MOTOR_CLAW_SPIN 8
#define MOTOR_BALL_LAUNCHER_1 1
#define MOTOR_BALL_LAUNCHER_2 10

#define INPUT_POWER_EXPANDER 12
#define INPUT_SPIN_ENCODER_TOP 1
#define INPUT_SPIN_ENCODER_BOTTOM 2
